### ISSUE TITLE
Feature Request | Simulating Fake Ping

### ISSUE THREAD

**Issue by megalithos** [RiptideNetworking/Riptide#100]
Option for developers to add 'fake' latency to the connection. For example if I am developing game and hosting the server on localhost (ping close to 0), I would be able to add latency, 200ms for example and debug bad internet connection based issues.

**Comment by tom-weiland** [comment]
I'm not ruling this out entirely, but I do wonder if it's really worth having this in the library itself.

I personally use [Clumsy](http://jagt.github.io/clumsy/) to simulate latency, packet loss, etc. and I think an external tool is better suited to the job because there's:
- no risk of accidentally leaving simulated loss in a build/release,
- no need for users to build a UI to set the value (without which it would need to be hard-coded, leading to version control changes),
- no additional overhead even when it's turned off (though in theory that should only be an if statement, so it wouldn't be *too* bad), and
- it's easier to change values on the fly.

**Comment by megalithos** [comment]
Now that I have used Clumsy a lot for debugging, I can say that this feature is totally not worth it for Riptide. Third party tool can be used with ease instead.

**Comment by tom-weiland** [comment]
I will close this for now then.
