### ISSUE TITLE
Feature Request | Message.Reserve & Message.Insert methods

### ISSUE THREAD

**Issue by megalithos** [RiptideNetworking/Riptide#103]
Would be useful to allow you to reserve bytes in a Riptide Message with method like (ints for example):
```cs
Message.ReserveInt();
```

And after that call you can add rest of the data and later call
```cs
Message.InsertInt(0, 123); // first parameter is index and second is the integer value
```

Here is at least one case where it is useful:
If you have code like
```cs
List<Player> validPlayers = Player.list.Values.Where(player => player.IsValid()).ToList();
Assert.IsTrue(validPlayers.Count <= byte.MaxValue); // player count shouldn't exceed byte.maxValue
message.AddByte((byte)validPlayers.Count);
for (int i = 0; i < validPlayers.Count; i++)
{
    Player player = validPlayers[i];
    AddPlayerMovementToPacket(player, message);
}
```
instead of iterating player list twice in total (worst case), you could in the beginning reserve space in the message for the 
count, then iterate the valid players and count them (so only need to iterate player list once)

And in the end you can just call InsertInt into the beginning.

**Comment by tom-weiland** [comment]
This is a good idea—do you think a specific method would be necessary for each type though? It might make it more beginner friendly, but would probably just be unnecessary bloat compared to having a single method which takes a parameter for the number of bytes to reserve 🤔

I think I'll implement this after making the `Message` class work on the bit-level (instead of the byte-level like it does now) to avoid the extra breaking change.

**Comment by megalithos** [comment]
In my opinion and according to the DRY principle you should have just one method for it.

Maybe you could have base function (which could be called directly): Message.ReserveBytes(int byteCount);

And generic helper function like: Message.Reserve<T>()
Which could be used e.g.: Message.Reserve<int>()

**Comment by damage991** [comment]
I’m so sick of reading this fucking thread I subbed to like 4 years ago. I’ve unsubbed so many times and can’t get out of it. No offense to anyone just wish I could get out of it.

Sent from my iPhone

On Jul 14, 2023, at 5:44 PM, Tom Weiland ***@***.***> wrote:

﻿

This is a good idea—do you think a specific method would be necessary for each type though? It might make it more beginner friendly, but would probably just be unnecessary bloat compared to having a single method which takes a parameter for the number of bytes to reserve 🤔

I think I'll implement this after making the Message class work on the bit-level (instead of the byte-level like it does now) to avoid the extra breaking change.

**Comment by tom-weiland** [comment]
> And generic helper function like: Message.Reserve T ()

Well a `Reserve` method that takes a parameter for the number of bytes could be used like `message.Reserve(sizeof(int))`, so I think a generic method would probably be overkill too.

**Comment by megalithos** [comment]
Yeah that's true. I don't think there is need to make it too beginner friendly because not many beginners will probably use it anyways 😅
