### ISSUE TITLE
Feature Request | Additional MessageSendModes

### ISSUE THREAD

**Issue by vakuor** [RiptideNetworking/Riptide#110]
Hello!

I think it's a good idea to add additional message send modes, like the ones in litenetlib.
I personally miss the following two in development:
- Reliable with order
- Reliable sequenced (realiable only last packet)

Reliable with order should prevent situation when packets mess around.
Reliable sequenced is useful for situation when you need to update some values for your game. It is like [Networked] header in mirror or unet.

**Comment by tom-weiland** [comment]
> Reliable with order should prevent situation when packets mess around.

What do you actually need this for? I have yet to run into a situation with my own project where the need for order would be better addressed by the messages being guaranteed to arrive in order (which always comes at the cost of added latency) than by manually ordering or discarding out of order data on the receiving end (depending on what suits the situation).

> Reliable sequenced is useful for situation when you need to update some values for your game. It is like [Networked] header in mirror or unet.

You'll have to elaborate on what exactly you mean by "reliable sequenced". I'm not sure I understand how that term specifically relates to "[updating] some values for your game" (as that's usually the purpose of sending any kind of message) or to the `[Networked]` attributed in other (higher level) solutions.

**Comment by vakuor** [comment]
> Reliable with order. What do you actually need this for?

I need this for situation when in your gameplay you need to calculate some things in correct order.
Currently to achieve this kind of behaviour you need to manually add smth like "order id". Write some additional code to handle order and only then do things you need.
Example is worms game where you send player's actions in order in which they should be simulated on other's computers.

> You'll have to elaborate on what exactly you mean by "reliable sequenced".

I may have confused the concepts a bit. Reliable sequenced means realiable only last packet. This type of message should check message reliability only until a new message of same type and receiver but with different values appears.

I need this for situation where I need to store only latest state of variable. For example health of player. When your health change rapidly you do not need to have all health messages be reliable. You need only to receive latest health message.

**Comment by tom-weiland** [comment]
> Example is worms game where you send player's actions in order in which they should be simulated on other's computers.

I can't imagine a player's actions are very big (bandwidth-wise), so is there a reason you can't send them all in one message?

> I need this for situation where I need to store only latest state of variable. For example health of player.

I recently added a "notify" send mode, which does something similar to what I think you need. It doesn't provide reliability, but it notifies you when the message is lost or delivered (hence the name). It's used a bit differently from the other send modes though—instead of `Message.Create()` you use `Message.CreateNotify()`, and there are no message IDs built in. To send the message, you send it directly through the `Connection` (instead of through the `Server`/`Client`) with `connection.SendNotify(messageGoesHere)`, which returns the sequence ID it was sent with. The connection will then invoke either the `NotifyDelivered` or `NotifyLost` event, depending on what happened to the message. To receive/handle notify messages, you can subscribe to the connection's `NotifyReceived` event.

Using the sequence IDs which the `SendNotify` method and `NotifyDelivered` and `NotifyLost` events spit out, you can track what happened to a given message and react accordingly. In your example, you could track the sequence ID of the latest message you've sent which contained the health value, and if it's lost, you simply send the health value again.

**Comment by Gohan500** [comment]
Hey there, if i might add a situation in which you would need a message to be in order.

This would be for instance a chat system.
If a player sends a chat message and another straight after, then the player would also expect the first message to be send and arrived first. other wise the second message might be send to other player as the first message instead of the second,

**Comment by tom-weiland** [comment]
> This would be for instance a chat system.

If you timestamp each chat message with the tick it was sent on, and maybe with the tick of the previous chat message, it'd be relatively easy to sort them on the receiving end.

Typically most game data does not need to be received/processed in order, but it *does* need to be delivered asap, and guaranteeing order adversely impacts delivery speed if the connection has any amount of packet loss, which is why I'm hesitant to add this into the library itself.

That being said since notify mode is now a thing (or rather, *will* be in the next update), any time sensitive game data could/probably should be sent that way and you could make the case that the reliable send mode should only be used for things which don't require asap delivery, and therefore having it guarantee order would make sense.

**Comment by fkavum** [comment]
Hi,

I also need this feature in my game. The situation is; 
Im making a turn based game. So, im sending startGame command and turnChange/gamePlay commands afterwards. if i cant have them in order, i have to cache them in client to wait previous desired command. There are also some movement commands that can be omitted in my game, thats why im using UDP, instead of TCP.

**Comment by tom-weiland** [comment]
Closing this as I don't see the need for or benefit from adding additional send modes outside of unreliable, reliable, and notify. The one thing I would consider is making reliable mode guarantee order, but this would be a substantial undertaking and require a major overhaul of how the reliable mode currently works.

**Comment by Per6** [comment]
I've implemented it myself: https://github.com/Per6/Riptide-Queued-Send-Mode
it is simply better than reliable and really doesn't add much latency,
especially when MaxSynchronousQueuedMessages is set high.
