### ISSUE TITLE
Server.MessageReceived dont work

### ISSUE THREAD

**Issue by jackduang** [RiptideNetworking/Riptide#112]

**Comment by jackduang** [comment]
I want the server to send the message to the client after receiving it

**Comment by tom-weiland** [comment]
> Server.MessageReceived dont work

In what way does the MessageReceived event not work? I use it all the time without issues, so you'll have to elaborate on what the problem is.

> I want the server to send all client messages to the client after receiving the message

Is this somehow related to the title? I don't understand the connection. Also, which client messages do you want to send to which clients? The [`Server.RelayFilter`](https://riptide.tomweiland.net/api/Riptide.Server.RelayFilter.html) can be used to make the server automatically "forward" messages to all *other* connected clients, which might be what you're looking for.

**Comment by tom-weiland** [comment]
Closing this due to insufficient information and lack of responses.
