### ISSUE TITLE
Can unity client connect to console server

### ISSUE THREAD

**Issue by huykhaduy** [RiptideNetworking/Riptide#116]
I used your console server demo to establish a connection with a Unity client, but it didn't work. However, when I used dedicated server demo and it worked. So do you know anyway to do that ? Thanks. I'm new to this.

**Comment by JingchengYang4** [comment]
I'm implementing it on console server <-> unity client right now, works perfectly. 

Check if your ports / ip are fine and there are no firewalls blocking your applications (since you already have console app, try to see if you can connect to a asp.net template to see if local host connections are restricted).

You could just copy the dedicated server demo to a console project too, if there are some code incompatibilities.

**Comment by tom-weiland** [comment]
@huykhaduy that's because the console demo is not compatible with the Unity demo(s), at least not without modifying them. They send different data (because they do different things), and they're not set up to understand each other—it's as though they're speaking two different languages.

You absolutely *can* set up a server/client in a console app and connect it to a client/server running in Unity, but you can't take the demos which do different things and expect them to work interchangeably as is.

**Comment by huykhaduy** [comment]
I just created a new console project and I realized that the firewall is causing the problem. Thanks for helping me.
