### ISSUE TITLE
Bug | Eating bytes if is count more than 32767 (Message only contains 7170 unread bytes, which is not enough to retrieve 72706 bytes! Returned array will contain default elements)

### ISSUE THREAD

**Issue by DPrison** [RiptideNetworking/Riptide#119]
I'l try to send message with 72706 bytes, but still get only 7170
Send Code: 
```
Message message = Message.Create(MessageSendMode.Reliable, 4);
message.AddInt(bytes.Length);
message.AddBytes(bytes, false);
server.Send(message, (ushort)playerId, false);
```
Recieve Code:
```
int bytesLength = message.GetInt();
manager.GetGameObjects(message.GetBytes(bytesLength));
```
But in the client console i see this
![image](https://github.com/RiptideNetworking/Riptide/assets/62451660/01ab984c-a3a5-40fa-a62a-85dcbe8239d7)
I try to change MessageSendMode to Reliable and Unreliable, disallow message releasing (it means to server.Send boolean "shouldRelease"), replace manually provided bytes length in int to message.UnreadLength, using other transports (Riptide.Transports.Udp and Riptide.Transports.Tcp), but nothing changes, i cannot down bytes count to 32767, so please help

**Comment by tom-weiland** [comment]
This sounds a lot like #92. Update to the latest dev package [via the Unity package manager](https://riptide.tomweiland.net/manual/overview/installation.html#option-1-unity-package-manager) (notice the "tip" about getting the dev package instead of the latest release) or clone the repo and build the dll yourself, whichever you prefer. There are some fixes in there that relate to large messages.

That being said, if I remember correctly UDP sockets will produce an error if you try to send more than ~65k bytes, so unless you're fine using TCP, you'll need to split your data up across multiple messages and reassemble it on the other end. Riptide is not built to send such unusually large messages (games normally don't need to send anywhere close to how much you're trying to send at once, aside from *maybe* when a client first connects), so doing it anyways requires a bit of extra work.

> I try to change MessageSendMode to Reliable and Unreliable, disallow message releasing

These have nothing to do with message size, so you can set those back to what you were using previously.

**Comment by DPrison** [comment]
Okay, this solve my problem, thanks
