### ISSUE TITLE
[Bug/Question] UnreadBits not zero after reading all data from Notify message

### ISSUE THREAD

**Issue by Charanor** [RiptideNetworking/Riptide#133]
When receiving a Notify message I noticed that `UnreadBits` is often not zero after reading all available data. I am unsure of this is intended - maybe messages include some footer? Seems to only happen when sending over the net. Here is a super tiny reproducible example:

```cs
// Client
var message = Message.Create(MessageSendMode.Notify);
message.AddInt(42);
SendMessage(message);


// Server
var val = message.GetInt();
var unreadBits = message.UnreadBits; // sometimes 3, sometimes 4, sometimes 11, seems slightly random
```

![image](https://github.com/RiptideNetworking/Riptide/assets/16232214/5fb2d254-4513-4ba3-84cf-b752447a2676)

**Comment by tom-weiland** [comment]
It's not so much "intended" as it is *expected*. Bytes are the smallest unit of data that you can send over the network, so if a message consists of 60 bits (7.5 bytes) it will be sent as 8 bytes, with the last 4 bits being empty "filler" data. The receiving end will see that it received 8 bytes and set the `writeBit` (which is used to calculate `UnreadBits`) to 8 bytes * 8 bits per byte = 64 bits, even though the last 4 bits technically shouldn't be interpreted as data.

To prevent this from happening, senders would have to write the total number of usable bits into the message itself (near the beginning) so the receiver can read it and know exactly where the data ends. I figured this extra overhead wasn't worth it, especially since it's easy to implement yourself if you really want/need it. Additionally, you probably shouldn't be relying on there being a specific number of bits left over for any logic decisions, as a malicious client could send more or less bits (or manipulate/lie about the length value) and thereby cause problems.

The number of "extra" `UnreadBits`  that remain after you read out all your data depends on how many bits it takes to round up to the nearest byte, meaning that you should never be seeing more than 7 "extra" bits on the receiving end. The fact that you say it's "sometimes 11" is very odd and shouldn't be happening unless you haven't read out all your "real" data...

In the example you gave, `UnreadBits` should always be returning 4. If it's changing/fluctuating then that's also concerning.

**Comment by Charanor** [comment]
Thank you! Lack of knowledge from me, I just assumed network data was sent as bits, now the padding makes sense. And I was not using it for any game logic, it was just something I noticed when I added some sanity-checks around the code, one of them checking that all data was read. I'll just change the check to account for this padding. Cheers!

**Comment by Charanor** [comment]
> "sometimes 11" is very odd and shouldn't be happening unless you haven't read out all your "real" data
Given my silly typo in my other issue I think this was also just user error, I went through and checked all my current messages and when they arrive they never have more than 7 bits of padding. My bad again 🙏
