### ISSUE TITLE
Reliability of reliable messages

### ISSUE THREAD

**Issue by Per6** [RiptideNetworking/Riptide#135]
I have updated my 2 year old version of riptide networking in my project and it feels like the reliability of reliable messages has dropped. It seems like about every 50th message exceeds the maximum attempts now. Is there some settings that i can change to increase the reliability and is this caused by a change in settings over versions or what?

**Comment by tom-weiland** [comment]
The following assumes you've updated to v2.1.x, where a message exceeding the maximum send attempts results in the client being disconnected.

Depending on which version you updated from, one change that may be contributing is the removal of multithreading. Riptide used to listen for messages on a separate thread, which also allowed heartbeat messages and acks to be processed independently of whatever was happening on the main thread.

Unfortunately, this complicated a lot of things and trying to ensure everything was thread safe become a bit of a nightmare, so I decided to remove the multithreading (as I didn't really see any worthwhile advantages to keeping it) which greatly simplified everything. However in hindsight, the one advantage of the multithreaded approach was the separate heartbeat/ack processing—now they're processed on the main thread, meaning that if the main thread is busy doing something resource intensive for a bit, acks don't get sent immediately upon receiving a message.

This can lead to increased resends (since the other end isn't acknowledging messages it's assumed they were lost) and sometimes that's enough to hit the max send attempts or to exceed the max average send attempts (or loss rate, in the case of Notify messages).

Usually people run into this when they are doing something CPU intensive like loading a scene, in which case temporarily setting `Connection.CanQualityDisconnect` to false (on both ends) addresses the issue.

If you're encountering this throughout your gameplay loop then *temporarily* disabling that isn't viable. You could:
1. Play around with the connection's `MaxSendAttempts`, `MaxAvgSendAttempts`, and `AvgSendAttemptsResilience` until you find settings which work. The default values seem to generally be okay but also haven't undergone much real-world testing, so don't be afraid to change them!
2. Set `Connection.CanQualityDisconnect` to false *permanently*. Note that if you do this, messages will be resent indefinitely (until they're acknowledged or the connection is closed) so you may want to implement your own system to disconnect clients based on connection quality—the `ConnectionMetrics` (accessible via `Connection.Metrics`) will be useful for that.
