### ISSUE TITLE
Seperate server and client library

### ISSUE THREAD

**Issue by bberka** [RiptideNetworking/Riptide#138]
I think it would be better if you seperate this library to 3 packages

1. Shared
2. Client
3. Server

Because what i see is when you do multiplayer you need db and more secure stuff happening and i don't see any reason why client need that data as well. If there is a reason that i am not aware of i like to learn

**Comment by tom-weiland** [comment]
I'm not sure I understand the problem...

> when you do multiplayer you need db and more secure stuff happening and i don't see any reason why client need that data as well.

So don't include it in the client build...? There is no "database stuff" in this library, so that's entirely in the hands of each dev to do as they think is best for their project.

The Riptide library is small enough that there's no real size/import speed benefit to splitting it up into several packages, and I don't see any other benefits to doing it either. It would just make it more annoying tedious to install, especially as it's not uncommon for a project to need both a `Server` and a `Client` instance—the most efficient way to develop a game is to have both the client and server logic in the same project and to just exclude sensitive stuff from client builds.

Perhaps I'm missing something, but it sounds like you may have a misunderstanding of what Riptide is and what purpose it fulfils?
