### ISSUE TITLE
MessageExtensionUnity.cs missing in Repo

### ISSUE THREAD

**Issue by ApfelTeeSaft** [RiptideNetworking/Riptide#140]
Hi again, so i am following the tutorial with version 1.1.0 installed, and i noticed you refered to a script found in the repository:
![Screenshot 2024-05-23 230619](https://github.com/RiptideNetworking/Riptide/assets/91074565/7a979b80-708e-4650-a018-d12157c0c69a)

However it got Removed from the repo along the way of development, do you by any chance have a backup of it, or am i just incredibly bad at looking with my own eyes?

**Comment by tom-weiland** [comment]
If you view the repo from the [v1.1.0 tag](https://github.com/RiptideNetworking/Riptide/tree/v1.1.0) (or [v1.2.0](https://github.com/RiptideNetworking/Riptide/tree/v1.2.0)), the file is where it is shown to be in the video. The Unity package files were moved to a separate branch with the release of v2.0.0, so that file is now found [here](https://github.com/RiptideNetworking/Riptide/blob/unity-package/Packages/Core/Runtime/UnitySpecific/MessageExtensions.cs).

If you have further questions or problems with following the videos, please ask [on Discord](https://discord.gg/tomweiland) instead and reserve GitHub issues for issues with Riptide itself.
