### ISSUE TITLE
Can you upgrade ushort client ids to 32 bit unsigned integers ?

### ISSUE THREAD

**Issue by CrossV4** [RiptideNetworking/Riptide#143]
Hi,

I am using this api about 1 years. But there is an issue that 16 bit int id is too small. You should increase that to at least 32 bit unsigned integer for handling too wide clients. Could you that ?

**Comment by Nincompatoot** [comment]
What do you mean? A ushort ranges from values of 0 to 65,535, how have you exceeded that limit? You should consider developing your own matchmaking system, or allow for custom IP addresses to be entered so player's can host servers on their own systems.

**Comment by tom-weiland** [comment]
As @Nincompatoot basically asked above, how is a `ushort`/16 bit integer "too small" for the client ID?

I can pretty much guarantee you that (with perhaps a few really niche exceptions) no game is going to have 65 thousand players connected *simultaneously* to a *single* server, and if that's something you're trying to achieve you should probably be building your own networking solution from scratch to exactly fit your requirements so you don't waste a drop of performance :P

In case you're asking for this because you're using the client ID to identify players across sessions, stop doing that. Client IDs are meant to identify a client while they're connected, and not any longer. If you need a unique, unchanging player ID you should be generating that yourself and associating it with the player's account, not using the client ID that Riptide assigns to connections.
