### ISSUE TITLE
(SERVER): Could not guarantee delivery of a Welcome message after 15 attempts! Disconnecting...

### ISSUE THREAD

**Issue by NetheriteOfficial** [RiptideNetworking/Riptide#145]
either i am stupid or it doesn't work, also if the client part is on the server part then it connects normally, but if i split it to 2 separate projects on a local PC then it doesn't even connect

**Comment by tom-weiland** [comment]
Do you have the Run in Background setting enabled in both projects? It used to be enabled by default in older Unity versions but that's no longer the case in newer versions, and without it enabled, the server/client will effectively stop executing (and become unresponsive) if it's not the active window.

**Comment by NetheriteOfficial** [comment]
What about bare C#? I am still getting the same error but in C#

**Comment by tom-weiland** [comment]
Without knowing exactly how you've set things up, there's really no way of saying what the issue might be. Are you calling the server's and client's `Update` methods regularly? Are you sure you split the projects correctly so that the separate client/server function the same way as the combined one?

**Comment by NetheriteOfficial** [comment]
I am calling Update in an while(_client.IsConnected) loop in both scenarios
