### ISSUE TITLE
when writing and reading a line the first character is lost

### ISSUE THREAD

**Issue by IKatyrov** [RiptideNetworking/Riptide#148]
![Снимок экрана 2024-08-31 012716](https://github.com/user-attachments/assets/65177615-6498-4248-b764-7a6e2daec9ab)

**Comment by tom-weiland** [comment]
You need to provide the `Message.Create` method with a message ID (ushort) if you're sending it via Reliable or Unreliable mode, *or* you need to manually add the message ID (via `message.AddUShort`) before anything else.

The overload you're using there which only takes the send mode as a parameter is intended for use with the Notify send mode (as indicated by the documentation/XML doc comments which should show in your intellisense) since that doesn't make use of message IDs.
