### ISSUE TITLE
Messages become unusable for no reason

### ISSUE THREAD

**Issue by Per6** [RiptideNetworking/Riptide#151]
Each of these debugs gives a different id and only the first one is getting sent properly:
`
Server
`
```
static Message test;

[MessageHandler(34)]
static void ResendTest(ushort fromClientId, Message message) {
	test = message;
	LaterDebug(0);
	LaterDebug(1);
	LaterDebug(1000);
}

static async void LaterDebug(int time) {
	await System.Threading.Tasks.Task.Delay(time);
	Debug.Log(test.GetId());
	NetworkManager.server.SendToAll(test, false);
}
```
`
Client
`
```
static void Testing() {
	Message msg = Message.Create(MessageSendMode.Reliable, 34);
	NetworkManager.client.Send(msg, false);
}

[MessageHandler(34)]
static void GotTest(Message _) {
	Debug.Log("recieved test");
}
```
`
MessageExtension
`
```
public static ulong GetId(this Message msg) {
	int currentBit = 20;
	ulong num = 0;
	int num2 = 0;
	ulong num3;
	do {
		msg.PeekBits(8, currentBit, out num3);
		num |= (num3 & 0x7F) << num2;
		currentBit += 8;
		num2 += 7;
	} while((num3 & 0x80) != 0L);
	return num;
}
```

**Comment by Per6** [comment]
https://github.com/RiptideNetworking/Riptide/pull/150#issuecomment-2323508158

**Comment by tom-weiland** [comment]
The debugs are presumably returning incorrect results because when you receive a message, it is released back to the pool as soon as your message handler method completes (so it can be reused). Messages are not meant to be used for storing data—you're supposed to retrieve the information you need and then be done with it.

If you absolutely *insist* on doing whatever you're doing the way that you're trying to do it, then you should take the message you receive in the message handler and copy it to a separate (completely empty) message instance via the [`AddMessage`](https://github.com/RiptideNetworking/Riptide/blob/main/RiptideNetworking/RiptideNetworking/Message.cs#L283) method. Then you can do what you want with it without Riptide automatically returning it to the pool.

**Comment by Per6** [comment]
That makes the `shouldRelease` parameter extremely misleading. I thought setting that to false would stop it from releasing back to the pool altogether.

**Comment by tom-weiland** [comment]
How exactly is it misleading? If a parameter on the `Send` method affected behaviour when receiving messages, that would be much more mislead, no? 🤔

The `shouldRelease` parameter only exists on the `Send` method (and its variants) because it only applies to the specific message instance you're sending (and only on that specific `Send` call). It's intended for situations where you might want to send the same message multiple times but with slight variations so you can send (without releasing), modify, and send again (perhaps releasing that time). It's a pretty niche use case and most people will never need to use the parameter.

If it applied to all messages at all times it should (and would) be a static property of the `Message` class, and if it applied to more than just a specific `Send` call then it would be a property on the message instance instead.

**Comment by Per6** [comment]
Ohh. Yeah it would have made way more sense to be set in the `Create`, not the `Send`
