### ISSUE TITLE
Feature Request: New Send mode with even better reliability

### ISSUE THREAD

**Issue by Per6** [RiptideNetworking/Riptide#152]
For turn based games, a single lost message can break the game and if someone disconnects,they just lose without a chance to reconnect, so i'd like the send mode "OverlyReliableQueue".

Each `Connection` would have a `Queue` of sent messages.
When sending with `OverlyReliableQueue` it would add the message to the `Queue` and if it is the first, then send it immideately.
When recieving confirmation, that the message arrived, it would remove the message from the `Queue` and send the next.
Each Heartbeat it should resend the first message of the `Queue`, in case it was lost.
In case a message was recieved multiple times, there would be a `ushort highestQueuedSequenceId` to check if it should be accepted.

`Connection` should also have a ClearQueue function in case i want to disconnect intentionally.

**Comment by Per6** [comment]
closed as it has been denied in https://github.com/RiptideNetworking/Riptide/pull/150

**Comment by tom-weiland** [comment]
I just wanted to add a more specific explanation since you laid out more specific requirements here: you could implement this on top of the Notify send mode.

1. Maintain your own message queue.
2. Send the first message via Notify.
3. Use the related `NotifyDelivered` and `NotifyLost` events to either send the next message from the queue or resend the one that was lost.

Notify send mode already filters duplicates (by sequence ID) so you shouldn't have to worry about that yourself.
