### ISSUE TITLE
Ability to have an asynchronous callback on reliable messages

### ISSUE THREAD

**Issue by xzippyzachx** [RiptideNetworking/Riptide#42]
The ability to have an asynchronous callback form a reliable message when it successfully arrives. This would allow you to do something that is only able to be done after a message is successfully received. The example I had was to send a message to spawn the player and then only send the message to spawn the players items after the player message was successfully received.

**Comment by tom-weiland** [comment]
I wonder if the best way to resolve this would be to just make the reliable send mode guarantee order, especially since most serious projects will want to send most time sensitive game data via the (recently added) notify send mode, so the reliable mode doesn't really need to prioritize delivery speed quite as much as it used to 🤔

**Comment by xzippyzachx** [comment]
I could also see this feature not really needed anymore or already possible by using the notify send mode. You could just handle re-sends on the application level. I haven't tried notify send mode yet though so it might not 100% be what I think it is. Would be nice for reliable send mode to guarantee order though.
